I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2467, in script call
    $ renpy.call(random_jump_target)
  File "game/script.rpy", line 2809, in script
    $ erros = erros + 1
  File "game/script.rpy", line 2809, in <module>
    $ erros = erros + 1
NameError: name 'erros' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2467, in script call
    $ renpy.call(random_jump_target)
  File "game/script.rpy", line 2809, in script
    $ erros = erros + 1
  File "C:\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 2809, in <module>
    $ erros = erros + 1
NameError: name 'erros' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
 Alpha9
Thu Aug 19 21:08:04 2021
